default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

#production:
#  <<: *default
#  database: db/production.sqlite3
